(define (same-parity first . rest)
  (define (helper lst)
    (cond ((null? lst) (list))
          ((= (remainder first 2) (remainder (car lst) 2))
           (cons (car lst) (helper (cdr lst))))
          (else (helper (cdr lst)))))
  (cons first (helper rest)))

(same-parity 1 2 3 4 5 6 7)
(same-parity 2 3 4 5 6 7)
